---
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo-1106
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o-2024-05-13
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-opus
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: llama-3-70b
    litellm_params:
      model: anyscale/meta-llama/Meta-Llama-3-70B-Instruct
      api_key: os.environ/ANYSCALE_API_KEY
  - model_name: mixtral-8x22B
    litellm_params:
      model: anyscale/mistralai/Mixtral-8x22B-Instruct-v0.1
      api_key: os.environ/ANYSCALE_API_KEY
  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY
litellm_settings:
  drop_params: true
general_settings:
  master_key: os.environ/MASTER_KEY
