model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o-2024-08-06
      api_key: os.environ/OPENAI_API_KEY
      rpm: 500
      tpm: 30000
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini-2024-07-18
      api_key: os.environ/OPENAI_API_KEY
      rpm: 500
      tpm: 30000
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      extra_headers: {"anthropic-version": "2023-06-01", "anthropic-beta": "prompt-caching-2024-07-31"}
      api_key: os.environ/ANTHROPIC_API_KEY
      rpm: 1000
      tpm: 80000
  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      extra_headers: {"anthropic-version": "2023-06-01", "anthropic-beta": "prompt-caching-2024-07-31"}
      api_key: os.environ/ANTHROPIC_API_KEY
      rpm: 1000
      tpm: 80000
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key: os.environ/GEMINI_API_KEY
litellm_settings:
  drop_params: true
router_settings:
  routing_strategy: simple-shuffle
  timeout: 60
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT
general_settings:
  master_key: os.environ/MASTER_KEY
environment_variables:
  AZURE_API_VERSION: 2024-10-01-preview
  REDIS_SSL: 1
